var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   " xxx yyy xxx yyy xxx yyy !!!!!!!!!! xxx yyy xxx yyy !!!!!!!!!! xxx yyy xxx yyy  ",
   "                                                                                ",
   "                                                                                ",
   "                                                                  xyx           ",
   "                                                   xx      xx    xy!yx          ",
   "                                    o o      xx                  xy!yx          ",
   "                                                                 xy!yx          ",
   "  xxxxxxx xxxxxxx xxxxxxx   xxxxxxx xxxxxxx xxxxxxx   xxxxxxx xxxxxxx xxxxxxx   ",
   "                                                                            xx  ",
   "                                                                             x  ",
   "                             yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy                ",
   "                            y x!!!x!xxxxx!x!!!!x!!!!xxxxx x x x y               ",
   "                            y x!!!x!x!!!!!x!!!!x!!!!x!!!x x x x y               ",
   "                            y xxxxx!xxx!!!x!!!!x!!!!x!!!x x x x y               ",
   "                            y x!!!x!x!!!!!x!!!!x!!!!x!!!x !!!!! y               ",
   "                            y x!!!x!xxxxx!xxxx!xxxx!xxxxx x x x y               ",
   "                             yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy                ",
   "                                                                                ",
   "                                                                                ",
   "  xxxxxxxxxxxx  xxx    yyy        xxxxx    yyy    xxxxx    yyy  yyy  xxxxxxxxx  ",
   "                              x   x                  x     x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxx  xxx xxxxxxxxxxxxxxxxxx xxxxx    yyyyyyyyyyy      ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   " xxx !!!!!!!!!!!!!xxxxxxx!!!!!!!!!!!!!!!!xxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!  xxx",
   "                                                                                ",
   "                                                                                ",
   "                                                                  xyx           ",
   "                                                   xx      xx    xy!yx          ",
   "                                    o o      xx                  xy!yx          ",
   "                                                                 xy!yx          ",
   "  xxxxxxxyxxxxxxx xxxxxxxyyyxxxxxxxyxxxxxxxyxxxxxxxyyyxxxxxxxyyyxxxxxxxyxxxxxx  ",
   "                                                                                ",
   "                                                                                ",
   "                             yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy         ",
   "                            y xxxxx!x!!!x!xxxx!!xxxxx!x!!!x!xxxx x x x y        ",
   "                            y x!!!x!!x!x!!x!!!!!x!!!x!!x!x!!x!!! x x x y        ",
   "                            y xxxx!!!!x!!!xxxx!!xxxx!!!!x!!!xxxx x x x y        ",
   "                            y x!!!x!!!x!!!x!!!!!x!!!x!!!x!!!x!!! !!!!! y        ",
   "                            y xxxxx!!!x!!!xxxx!!xxxxx!!!x!!!xxxx x x x y        ",
   "                             yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy         ",
   "                                                                                ",
   "                                                                                ",
   "  xxxxxxxxxxxx  xxx    yyy        xxxxx    yyy    xxxxx    yyy  yyy  xxxxxxxxx  ",
   "                              x   x                  x     x                    ",
   "                              xyyyx!!!!!!!!!!!!!!!!!!xyyyyyx                    ",
   "                              xyyyx!!!!!!!!!!!!!!!!!!xyyyyyx                    ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxx  xxx xxxxxxxxxxxxxxxxxx xxxxx    yyyyyyyyyyy      ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                xxxxxxxxxxxxxxxxxxxxxxx                           xyx           ",
   "            xxxx                                   xx      xx    xy!yx          ",
   "         xxx                        o o xx   xx                  xy!yx          ",
   "      xxx                              xx                        xy!yx          ",
   "  xxxxxxx xxxxxxx xxxxxxx   xxxxxxx xxxxxxx xxxxxxx   xxxxxxx xxxxxxx xxxxxxx   ",
   "                                                                            x   ",
   "                                                                                ",
   "                             yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy                ",
   "                            y x           x  x  xx    x  x x x y                ",
   "                            y  x         x   x  x x   x  x x x y                ",
   "                            y   x   x   x    x  x  x  x  x x x y                ",
   "                            y    x x x x     x  x   x x        y                ",
   "                            y     x   x      x  x    xx  x x x y                ",
   "                             yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy                ",
   "                                                                                ",
   "                                                                                ",
   "  xxxxxxxxxxxx  xxx    yyy        xxxxx    yyy    xxxxxxxxxyyy  yyy  xxxxxxxxx  ",
   "                              xxxxx                  x!!!!!x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxx  xxx xxxxxxxxxxxxxxxxxx xxxxx    xxxxxxxxxxx      ",
   "                                                                                ",
   "                                                                                "];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
